title: Pyae Phyo Kyaw
logo: /assets/img/My Photo.png
description: Data Analyst
description: Email: ppk.edu2000@gmail.com / Phonenumber: +66 633453371
theme: jekyll-theme-minimal
github:
  is_project_page: false
