title: Pyae Phyo Kyaw
logo: /assets/img/My Photo.png
description: Data Analyst          Email - ppk.edu2000@gmail.com          Phone - +66 633453371
theme: jekyll-theme-minimal
github:
  is_project_page: false
